### ISSUE TITLE
Add @reporters/junit

### ISSUE THREAD

**Issue by dancastillo** [mcollina/borp#101]
Looking to add `@reporters/junit` to satisfy fastify's `npm run unit:junit` [script](https://github.com/fastify/fastify/blob/main/package.json#L28). For using borp on migration from `tap` to `node:test` so not to install in fastify dev dependencies [ref](https://github.com/fastify/fastify/pull/5720)

If this is wanted I can try to implement

**Comment by jsumners** [comment]
We wouldn't need to add it into `borp`. We'd `npm install -D @reporters/junit` and then `borp -r @reporters/junit`. However, there's no need for the junit report in Fastify's CI as far as I can tell. It was probably needed by a disused coverage service. Simply remove the script from Fastify's project manifest.
