### ISSUE TITLE
Why Borp?

### ISSUE THREAD

**Issue by stuft2** [mcollina/borp#27]
It's not clear to me what this packages accomplishes that the Node.js test runner can't already do by adding `--import=tsimp/import ./test/*.{js|ts}` when calling `node --test`. There's even test coverage via the `--experimental-test-coverage` flag. Could you provide a set of features to the readme that this package aims to provide that the Node.js test runner does not support? There may be things that this package simplifies for developers and that would be great to know as well.

**Comment by mcollina** [comment]
A few reasons:

1. `tsimp` has never worked reliably for me, leaving multiple processes around in my system
2. quite a few features here are not available in Node.js v18.
3. `--experimental-code-coverage` cannot be triggered from the `run`

but TL;DR if you need this module is here. If not, just use the runtime
