### ISSUE TITLE
Initial File for Testing

### ISSUE THREAD

**Issue by Fyrlex** [mcollina/borp#28]
Hi, I am trying to test my Mongoose models with this, however I want to be able to run an initial `before` hook that connects mongoose to my database. The screenshot below is my file setup. When I run the `borp --coverage` command it seems to (maybe obviously) run the user and guild first. Is/can there be a way to specifiy a file that runs first so I can setup some `before` or `beforeEach` hooks?

![image](https://github.com/mcollina/borp/assets/31144090/cdb63f62-552b-421f-b0bc-a424094f8dc4)

Thank you for creating this package!

**Comment by mcollina** [comment]
You can create an `helper.ts` file that has a `bootDB()` export that set things up properly.
Would that work for you?

**Comment by Fyrlex** [comment]
Yes, thank you!
