### ISSUE TITLE
[Feature] Flag to enable node's garbage collector

### ISSUE THREAD

**Issue by anurag-roy** [mcollina/borp#3]
I want to enable node's garbage collector for some of my tests, but there is no flag to do so using borp.

A flag like `--expose-gc` which I could pass to borp, would be nice.

### Current Behaviour

Currently I have to do something like:
```
node --expose-gc node_modules/.bin/borp --coverage test/fetch/fetch-leak.js
```

### Desired Behaviour
```
borp --expose-gc --coverage test/fetch/fetch-leak.js
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by anurag-roy** [comment]
@mcollina Yes I'd more than love to!

**Comment by mcollina** [comment]
go for it!
