### ISSUE TITLE
Proposal: Automatically set --enable-source-maps when sourceMap is active in tsConfig.json

### ISSUE THREAD

**Issue by Palaxx** [mcollina/borp#32]
Hello, 

Running borp without additional configurations does not generate the source maps files, even if **sourceMap** is active in `tsconfig.json` file.

I know we can achive the goal setting the **NODE_OPTIONS** enviroment variable before running the tests, somenthing like this
```shell
NODE_OPTIONS=--enable-source-maps borp ...
```
but probably we can automatically set it from borp only if `sourceMap=true` exists in `tsconfig.json`.
What do you think about it? 
If you think it is ok, i can open a new PR in the next days

**Comment by mcollina** [comment]
Definitely! Would you like to send a PR?

**Comment by Palaxx** [comment]
Sure I'll do in the next days. 
Thanks
